### PR TITLE
Scaffold and configure the app

### LINKED ISSUE #2: intialize the project
- [x] scaffold the project's backend and frontend and link them together
- [x] incorporate linting and style verification
- [x] add testing support
- [x] deploy staging and production environments
- [x] add the project's information and steps to setup the project locally in `readme.md`

### PR DESCRIPTION
**Pull request by lunify**
Closes #2  
Initializes our project as a variant of a monorepo, with backend taking care of git-related scripts. The PR includes:
- [x] backend and frontend scaffolding
- [x] support for a local database
- [x] initial project folder structure
- [x] linting checks and automatic formatting
- [x] testing using jest
- [x] deployment configuration
- [x] project documentation and setup via `readme`

I had to make a workaround for linting checks on commits to work, which made the root's `package.json` hold both the client and the server's eslint plugins.

### CODE REVIEW

**Review by SebastianLF — COMMENTED** [review]
Do you think the cors middleware belongs here? 
I think If we don’t set up a CORS policy on the server, any http request coming from another domain will fail.
I myself often use this CORS package for express: https://www.npmjs.com/package/cors

**Comment by lunify** [comment]
@zelol apologies for the late reply, I didn't have notifications for this repo's discussions setup.

Great observation! Indeed, as it stands right now, a cross origin request will not be allowed on production environments. I figured we'd only add a CORS middleware (like the excellent [cors for express](https://www.npmjs.com/package/cors)) if/when we start making cross origin requests from our api, which is not the intended purpose for our design (correct me if I'm wrong).

As for local environments, I recall cors being very handy since having a frontend and a backend on 2 ports on localhost counts as having different origins, which blocks requests. A nifty alternative solution to that would be proxying api requests which gets rid of the problem (In our case, it can be done through the usage of a `proxy` property on the frontend's `package.json` with the url of our backend as the value).

Feel free to expand on the conversation if my answer was off the mark, or you have more to point out :smiley:

**Comment by lunify** [comment]
We will need a CI solution to run tests before PR merges. This is directly tied to testing, and should be researched and hopefully implemented. I'll try to look into it. If anyone has prior experience using CI tools, share the knowledge :smiley:

**Review by fletcher-greg — APPROVED** [review]
Thank you for setting this up

**Review by SebastianLF — APPROVED** [review]

**Pull request merged**
