### PR TITLE
Feature/login page

### PR DESCRIPTION
**Pull request by fletcher-greg**
### TODO:
-  Incorporate React-Hooks-Forms
-  Add API endpoint
-  Clean up styling and code

### CODE REVIEW

**Comment by SebastianLF** [comment]
Photo is clean, love it.
Very good UX for the errors handling in form.

Bug: 
- Poppins font is not applied to text.

Question:
- #4E63EE should be our recurrent main color. What do you think?

**Comment by fletcher-greg** [comment]
Thank you for the review 

I'll fix the Poppins bug.  

I agree that #4E63EE should be our main colour 😀

**Comment by lunify** [comment]
Hello ! What's the state of this PR @fletcher-greg ?

**Comment by fletcher-greg** [comment]
The login and register page need to be connected to the API.  

Styling for both forms need to be updated to reflect theme of the app.

**Comment by fletcher-greg** [comment]
Closed and reassigned to #43

**Pull request closed without merging**
