### PR TITLE
Feature/landing page

### PR DESCRIPTION
**Pull request by Moniet**

### CODE REVIEW

**Comment by SebastianLF** [comment]
@Moniet I've run the landing page on local and I love it!
One thing, when I click on the search bar a weird squared outline appear. I solved this by adding outline: none to the input css.
Also, the placeholder text of the search bar is in black color and is a bit hard to read. Can you change it to white?

**Review by fletcher-greg — COMMENTED** [review]
@SebastianLF @Moniet We ready to merge?

**Review by fletcher-greg — DISMISSED** [review]
ready for merge

**Review by fletcher-greg — APPROVED** [review]

**Comment by SebastianLF** [comment]
Tested locally and it works, Ready to merge!

**Review by SebastianLF — APPROVED** [review]

**Comment by lunify** [comment]
Great work on the PR ! I love the work :)

Regarding the merge blocker, should I disable the signed commit requirement ? Even though it's a best practice, if it's making more issues than it's worth, then I believe it might be best to omit it for the time being and let PRs like this pass. Alternatively, @Moniet can sign the commits and update the PR, which would solve the problem

Edit: I will go ahead and close it since it's a duplicate. See #27

**Comment by lunify** [comment]
duplicate of #27

**Pull request closed without merging**
